version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3
    restart: unless-stopped
    hostname: my-rabbit
    ports:
      - 5672:5672

  mqtt-broker:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ${MQTT_BROKER_CONFIG:-./mosquitto.conf}:/mosquitto/config/mosquitto.conf

  bacnet-app:
    image: bacnet-app:1.0
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
    volumes:
      - ${BACNET_BRIDGE_CONFIG:-./bacnet_bridge_config.toml}:/usr/src/app/config.toml
    depends_on:
      - rabbitmq  

  mqtt-client:
    image: mqtt-client:1.0
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/London}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
    volumes:
      - ${BACNET_BRIDGE_CONFIG:-./bacnet_bridge_config.toml}:/usr/src/app/config.toml 
    depends_on:
      - rabbitmq
      - mqtt-broker

